baseURL = "https://www.littlezhang.com/"
title = "理头张的博客"
theme = ["hugo-cloak-email", "hugo-notice", "hugo-notepadium"]
copyright = "©2017-2020 理头张"

languageCode = "zh-cn"
hasCJKLanguage = true
defaultContentLanguage = "zh-cn"

enableRobotsTXT = true
paginate = 7
enableEmoji = true

# Enable Disqus
#disqusShortname = "XXX"

# Google Analytics
#googleAnalytics = "UA-123-45"

[markup.highlight]
codeFences = true
guessSyntax = true
noClasses = true
style = "friendly"

[markup.goldmark.renderer]
unsafe = true  # enable raw HTML in Markdown

[permalinks]
  post = "/:year/:month/:title/"

[author]
    name = "理头张"

[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"

[params]
author = "理头张"
description = "littlezhang's blog"
style = "auto"  # default: auto. light: light theme, dark: dark theme, auto: based on system.
logo = "https://cdn.jsdelivr.net/gh/qidongz/qidongz.github.io/imgs/logo.png"
slogan = ""
#license = "<a rel=license href=http://creativecommons.org/licenses/by-nc-sa/4.0/><img alt=Creative Commons License style=border-width:0 src=https://i.creativecommons.org/l/by-nc-sa/4.0/88x31.png /></a><br />This work is licensed under a <a rel=license href=http://creativecommons.org/licenses/by-nc-sa/4.0/>Creative Commons Attribution-NonCommercial-ShareAlike 4.0 International License</a>."

[params.assets]
css = ["css/fonts.css"]

[params.comments]
enable = false  # En/Disable comments globally, default: false. You can always enable comments on per page.

[params.math]
enable = false # load math globally, default: false. You can always enable math on per page.
use = "katex"  # builtin: "katex", "mathjax".  default: "katex"

[params.nav]
showCategories = false       # /categories/
showTags = false             # /tags/

[[params.nav.custom]]
title = "首页"
url = "/"

[[params.nav.custom]]
title = "标签"
url = "/tags/"

[[params.nav.custom]]
title = "系列"
url = "/series/"

[[params.nav.custom]]
title = "归档"
url = "/archives/"

[[params.nav.custom]]
title = "关于"
url = "/about/"
