baseURL = "https://www.littlezhang.com/"
title = "理头张的博客"
theme = "hugo-notepadium"
copyright = "©2017-2020 理头张"

languageCode = "zh-cn"
hasCJKLanguage = true

enableRobotsTXT = true
paginate = 7
enableEmoji = true

# Enable Disqus
#disqusShortname = "XXX"

# Google Analytics
#googleAnalytics = "UA-123-45"

[markup.highlight]
codeFences = true
guessSyntax = false
noClasses = true
style = "xcode"

[markup.goldmark.renderer]
unsafe = true  # enable raw HTML in Markdown

[params]
author = "理头张"
description = "littlezhang's blog"
style = "auto"  # default: auto. light: light theme, dark: dark theme, auto: based on system.
logo = "/logo.png"
slogan = ""
#license = "<a rel=license href=http://creativecommons.org/licenses/by-nc-sa/4.0/><img alt=Creative Commons License style=border-width:0 src=https://i.creativecommons.org/l/by-nc-sa/4.0/88x31.png /></a><br />This work is licensed under a <a rel=license href=http://creativecommons.org/licenses/by-nc-sa/4.0/>Creative Commons Attribution-NonCommercial-ShareAlike 4.0 International License</a>."

[params.assets]
css = ["css/fonts.css", "css/shadow.css"]

[params.comments]
enable = false  # En/Disable comments globally, default: false. You can always enable comments on per page.

[params.math]
enable = false # load math globally, default: false. You can always enable math on per page.
use = "katex"  # builtin: "katex", "mathjax".  default: "katex"

[params.nav]
showCategories = false       # /categories/
showTags = false             # /tags/

[[params.nav.custom]]
title = "首页"
url = "/"

[[params.nav.custom]]
title = "标签"
url = "/tags/"

[[params.nav.custom]]
title = "分类"
url = "/categories/"

[[params.nav.custom]]
title = "关于"
url = "/about/"
